### ISSUE TITLE
Getting Escape Sequences in my values

### ISSUE THREAD

**Issue by silverbp** [reidmv/puppet-module-yamlfile#6]
Gettting "[\x22{value}\x22]" instead of "{value}".

I'm trying to configure ldap for the puppet master and have the following in the manifest:

```
yaml_setting { 'ad_cas_client_config':
    target => '/etc/puppetlabs/console-auth/cas_client_config.yml',
    key    => 'authorization/ldap/default_role',
    value  => 'read-only',
}
```

This ouptputs:

```

---
authorization:
  ldap:
    default_role: "[\x22read-only\x22]"
  local:
    default_role: "[\x22read-only\x22]"
    description: "[\x22Local\x22]"
...
```
